name: Building KeePassXC in Windows
on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    env:
      VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"
      VCPKG_ROOT: 'C:\vcpkg'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Export GitHub Actions Cache Environment
        uses: actions/github-script@v7
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      # 1. Get Cache
      - name: Get Cache
        uses: actions/cache@v4
        with:
          path: build
          key: build-${{ runner.os }}-${{ hashFiles('CMakeLists.txt') }}-${{ github.sha }}
          restore-keys: build-${{ runner.os }}-${{ hashFiles('CMakeLists.txt') }}-

      - name: Configure CMake
        run: |
           cmake -G Ninja -S . -B build `
            -DCMAKE_BUILD_TYPE=Release `
            -DCMAKE_TOOLCHAIN_FILE="C:/vcpkg/scripts/buildsystems/vcpkg.cmake" `
            -DWITH_XC_ALL=ON `
            -DWITH_XC_SSHAGENT=OFF `
            -DWITH_XC_NETWORKING=OFF `
            -DDWITH_XC_KEESHARE=OFF `
            -DCMAKE_SYSTEM_VERSION=10.0.22621.0

